# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-13 14:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0003_sessionlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='cmd',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='auditlog',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='session',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='audit.SessionLog'),
            preserve_default=False,
        ),
    ]
