# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-17 08:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0004_auto_20170813_1413'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('val', models.CharField(max_length=128)),
                ('expire', models.IntegerField(default=300, verbose_name='TimeOut(s)')),
                ('date', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='audit.Account')),
                ('host_user_bind', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='audit.HostUserBind')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='logintoken',
            unique_together=set([('host_user_bind', 'val')]),
        ),
    ]
