# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-17 10:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0005_auto_20170817_0839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logintoken',
            name='val',
            field=models.CharField(max_length=128, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='logintoken',
            unique_together=set([]),
        ),
    ]
